version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - tika
    command: /gunicorn.sh
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file: .env

  caddy:
    build: ./compose/caddy
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - caddy:/root/.caddy
      - ./media:/var/www/app/media
      - ./static:/var/www/app/static
    env_file: .env

  redis:
    image: redis:3.0

  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    volumes:
      - ./esdata:/data
      - ./eslogs:/logs
    expose:
      - "9200"

  tika:
    build: ./compose/tika
