# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileattachments', '0002_auto_20170825_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=100, verbose_name="File's Name"),
        ),
    ]
