# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import fileattachments.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fileattachments', '0003_fileattachment_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to=fileattachments.utils.get_upload_path, validators=[fileattachments.utils.file_validate]),
        ),
    ]
