# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='extended_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Extended Day (days)'),
        ),
    ]
