# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
    ]
