# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update')),
                ('control_item', models.CharField(choices=[('1', 'File new application'), ('2', 'File Chinese description'), ('3', 'Request examination'), ('4', 'File patent invalidation'), ('5', 'File re-examination'), ('6', 'File amendment'), ('7', 'File response'), ('8', 'Pay issue fee'), ('9', 'Pay maintenance fee'), ('10', 'Pay annuity fee'), ('11', 'File appeal'), ('12', 'File re-appeal'), ('13', 'File administrative litigation'), ('14', 'Other')], max_length=30, verbose_name='Control Item')),
                ('control_date', models.DateField(verbose_name='Control Date')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('complete_date', models.DateField(blank=True, null=True, verbose_name='Complete Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='patent',
            name='control_date',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='control_item',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='deadline',
        ),
        migrations.AddField(
            model_name='controlevent',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Patent'),
        ),
    ]
