# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number_employee',
            field=models.CharField(blank=True, choices=[('above', 'Above 500 employees'), ('under', 'Under 500 employees')], max_length=30, verbose_name='Number of employees'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='VAT No.'),
        ),
    ]
