# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='agent_ref_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='Agent Ref. No.'),
        ),
        migrations.AddField(
            model_name='patent',
            name='client_ref_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='Client Ref. No.'),
        ),
    ]
