# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent',
            old_name='IDS_infomation',
            new_name='IDS_information',
        ),
    ]
