# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='application_type',
            field=models.CharField(blank=True, choices=[('invention', 'Invention'), ('utility', 'Utility'), ('design', 'Design'), ('trademark', 'Trademark')], max_length=30, verbose_name='Type'),
        ),
    ]
