# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Home Number'),
        ),
    ]
