# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170620_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='foreign_agent',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='local_agent',
        ),
        migrations.AddField(
            model_name='patent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_agent', to='proposals.Agent', verbose_name='Agent'),
        ),
    ]
