# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_patent_extended_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='extended_date',
            field=models.IntegerField(blank=True, default=0, verbose_name='Extended Day (days)'),
        ),
    ]
