# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170605_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='client',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='work',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
    ]
