# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170624_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevent',
            name='patent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_event', to='proposals.Patent'),
        ),
    ]
