# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0002_auto_20170803_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update')),
                ('proposal_no', models.CharField(max_length=50, verbose_name='Proposal No.')),
                ('chinese_title', models.CharField(max_length=200, verbose_name='Chinese Title')),
                ('english_title', models.CharField(max_length=200, verbose_name='English Title')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Technique category')),
                ('proposal_date', models.DateField(blank=True, null=True, verbose_name='Proposal Date')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='Default Filing Countries')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('performance', models.CharField(blank=True, max_length=200, verbose_name='Applied field and performance')),
                ('appraisal_date', models.DateField(blank=True, null=True, verbose_name='Appraisal date')),
                ('appraisal_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('re-appraise', 'Re-appraise after supplements')], max_length=200, verbose_name='Appraisal Results')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventor',
            name='client',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='client',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='client_ref_no',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='proposal',
            name='inventors',
            field=models.ManyToManyField(to='proposals.Inventor', verbose_name='Inventors'),
        ),
    ]
