# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20170617_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person2',
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Contact Person's Email"),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Contact Person's Name"),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name="Contact Person's Phone Number"),
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_person_title',
            field=models.CharField(blank=True, max_length=30, verbose_name="Contact Person's Title"),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Contact Person's Email"),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Contact Person's Name"),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name="Contact Person's Phone Number"),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_title',
            field=models.CharField(blank=True, max_length=30, verbose_name="Contact Person's Title"),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.Client', verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='application_type',
            field=models.CharField(choices=[('', '---------'), ('invention', 'Invention'), ('utility', 'Utility'), ('design', 'Design')], default='', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='case_status',
            field=models.CharField(choices=[('', '---------'), ('1', 'Draft/Translation'), ('2', 'Preliminary examination'), ('3', 'Response/Amendment-1'), ('4', 'Response/amendment-2'), ('5', 'Rejection'), ('6', 'Publication'), ('7', 'Re-examination'), ('8', 'Appeal'), ('9', 'Re-appeal'), ('10', 'Administrative litigation'), ('11', 'Paying issue fee'), ('12', 'Patent allowed'), ('13', 'Client abandon'), ('14', 'Invalidation examination')], default='', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.Client'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='control_date',
            field=models.DateField(blank=True, null=True, verbose_name='Control Date'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='control_item',
            field=models.CharField(choices=[('', '---------'), ('1', 'File new application'), ('2', 'File Chinese description'), ('3', 'Request examination'), ('4', 'File patent invalidation'), ('5', 'File re-examination'), ('6', 'File amendment'), ('7', 'File response'), ('8', 'Pay issue fee'), ('9', 'Pay maintenance fee'), ('10', 'Pay annuity fee'), ('11', 'File appeal'), ('12', 'File re-appeal'), ('13', 'File administrative litigation'), ('14', 'Other')], default='', max_length=30, verbose_name='Control Item'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='foreign_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_foreign_agent', to='proposals.Agent'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='inventor',
            field=models.ManyToManyField(blank=True, to='proposals.Employee', verbose_name='Inventor'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='local_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_local_agent', to='proposals.Agent'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='owner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Owner'),
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
    ]
