# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20170820_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='inventors',
            field=models.ManyToManyField(to='proposals.Inventor', verbose_name='Inventor'),
        ),
    ]
