# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20170617_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='representative',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='agent',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beneficiary Name'),
        ),
        migrations.AddField(
            model_name='agent',
            name='beneficiary_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beneficiary A/C No.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='remittance_bank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Remittance Bank'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_employee',
            field=models.CharField(choices=[('above', 'Above 500 employees'), ('under', 'Under 500 employees')], default='under', max_length=30, verbose_name='Number of employees'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_id',
            field=models.CharField(choices=[('', '---------'), ('1', 'CEO'), ('2', 'Director'), ('3', 'Manager'), ('4', 'Senior Engineer'), ('4', 'Engineer')], default='', max_length=30, verbose_name='Title ID'),
        ),
    ]
