# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20170621_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_term_activation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10, verbose_name='Patent Term. Activation'),
        ),
    ]
