# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_patent_patent_term_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='description_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of description pages'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='drawing_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of drawing pages'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='extended_days',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Extended Days (days)'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='figures_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of figures'),
        ),
    ]
