# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170821_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='case_status',
            field=models.CharField(blank=True, choices=[('1', 'Draft/Translation'), ('2', 'Preliminary examination'), ('3', 'Response/Amendment-1'), ('4', 'Response/amendment-2'), ('5', 'Rejection'), ('6', 'Publication'), ('7', 'Re-examination'), ('8', 'Appeal'), ('9', 'Re-appeal'), ('10', 'Administrative litigation'), ('11', 'Paying issue fee'), ('12', 'Allowed'), ('13', 'Abandoned'), ('14', 'Invalidation examination')], max_length=30, verbose_name='Status'),
        ),
    ]
