# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0006_auto_20170822_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Latest Update'),
        ),
    ]
