# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20170617_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number_employee',
            field=models.CharField(blank=True, choices=[('0', '----------'), ('above', 'Above 500 employees'), ('under', 'Under 500 employees')], default='0', max_length=30, verbose_name='Number of employees'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_id',
            field=models.CharField(blank=True, choices=[('0', '---------'), ('1', 'CEO'), ('2', 'Director'), ('3', 'Manager'), ('4', 'Senior Engineer'), ('4', 'Engineer')], default='0', max_length=30, verbose_name='Title ID'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='application_type',
            field=models.CharField(blank=True, choices=[('0', '---------'), ('invention', 'Invention'), ('utility', 'Utility'), ('design', 'Design')], default='0', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='case_status',
            field=models.CharField(blank=True, choices=[('0', '---------'), ('1', 'Draft/Translation'), ('2', 'Preliminary examination'), ('3', 'Response/Amendment-1'), ('4', 'Response/amendment-2'), ('5', 'Rejection'), ('6', 'Publication'), ('7', 'Re-examination'), ('8', 'Appeal'), ('9', 'Re-appeal'), ('10', 'Administrative litigation'), ('11', 'Paying issue fee'), ('12', 'Patent allowed'), ('13', 'Client abandon'), ('14', 'Invalidation examination')], default='0', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='control_item',
            field=models.CharField(blank=True, choices=[('0', '---------'), ('1', 'File new application'), ('2', 'File Chinese description'), ('3', 'Request examination'), ('4', 'File patent invalidation'), ('5', 'File re-examination'), ('6', 'File amendment'), ('7', 'File response'), ('8', 'Pay issue fee'), ('9', 'Pay maintenance fee'), ('10', 'Pay annuity fee'), ('11', 'File appeal'), ('12', 'File re-appeal'), ('13', 'File administrative litigation'), ('14', 'Other')], default='0', max_length=30, verbose_name='Control Item'),
        ),
    ]
