# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20170617_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='contact_person_title',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='office_number',
        ),
    ]
