# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_remove_patent_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='patent_term_activation',
        ),
        migrations.AddField(
            model_name='patent',
            name='final_patent_term',
            field=models.DateField(blank=True, null=True, verbose_name='Final Patent Term.'),
        ),
    ]
