# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20170617_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_id',
            field=models.CharField(blank=True, choices=[('0', '---------'), ('1', 'CEO'), ('2', 'Director'), ('3', 'Manager'), ('4', 'Senior Engineer'), ('5', 'Engineer')], default='0', max_length=30, verbose_name='Title ID'),
        ),
    ]
